#pragma once

#include <Nxp.h>

enum SHAPE_TYPE
{
	SHAPE_SPHERE = NX_SHAPE_SPHERE,
	SHAPE_BOX = NX_SHAPE_BOX,
	SHAPE_CAPSULE = NX_SHAPE_CAPSULE,
};

enum JOINT_TYPE
{
	JOINT_PRISMATIC = NX_JOINT_PRISMATIC,
	JOINT_REVOLUTE = NX_JOINT_REVOLUTE,
	JOINT_CYLINDRICAL = NX_JOINT_CYLINDRICAL,
	JOINT_SPHERICAL = NX_JOINT_SPHERICAL,
	JOINT_POINT_ON_LINE = NX_JOINT_POINT_ON_LINE,
	JOINT_POINT_IN_PLANE = NX_JOINT_POINT_IN_PLANE,
	JOINT_DISTANCE = NX_JOINT_DISTANCE,
	JOINT_PULLEY = NX_JOINT_PULLEY,
	JOINT_FIXED = NX_JOINT_FIXED,
	JOINT_D6 = NX_JOINT_D6,
};

enum CONTROL_TYPE
{
	CONTROL_DYNAMIC = 1,
	CONTROL_KINEMATIC,
	CONTROL_STATIC,
};

enum ACTOR_AXIS
{
	AA_X_PLUS,
	AA_Y_PLUS,
	AA_Z_PLUS,
	AA_X_MINUS,
	AA_Y_MINUS,
	AA_Z_MINUS,
};
